In [1]:
from __future__ import print_function
import torch

In [3]:
x = torch.empty(5, 3)
print(x)

tensor(1.00000e-04 *
       [[ 0.0000, -0.0000,  0.0000],
        [-0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000, -0.0000,  1.4693]])


In [5]:
x = torch.rand(5, 3)
print(x)

tensor([[ 0.2021,  0.7909,  0.4036],
        [ 0.1633,  0.4257,  0.8655],
        [ 0.7075,  0.2166,  0.9747],
        [ 0.1596,  0.7281,  0.5322],
        [ 0.8754,  0.3000,  0.2877]])


In [6]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]])


In [7]:
x = torch.tensor([5.5, 3])
print(x)

tensor([ 5.5000,  3.0000])


In [11]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]], dtype=torch.float64)
tensor([[ 0.0687,  0.2375, -1.6844],
        [-0.3552,  1.2675,  0.3250],
        [-0.5181,  0.8833, -2.0856],
        [ 0.1109,  1.4638, -0.0891],
        [ 0.9325, -1.1315, -0.0728]])


In [12]:
print(x.size())

torch.Size([5, 3])
