In [24]:
import torch
import numpy as np

In [25]:
x = torch.rand(5, 3)
y = torch.rand(5, 3)

In [26]:
x + y

tensor([[ 0.7458,  1.4097,  1.0100],
        [ 1.0252,  0.6327,  0.8803],
        [ 1.3238,  0.6725,  1.2268],
        [ 1.0162,  1.4206,  0.7989],
        [ 0.9007,  0.9021,  1.3954]])

In [27]:
result = torch.add(x, y)
print(result)

tensor([[ 0.7458,  1.4097,  1.0100],
        [ 1.0252,  0.6327,  0.8803],
        [ 1.3238,  0.6725,  1.2268],
        [ 1.0162,  1.4206,  0.7989],
        [ 0.9007,  0.9021,  1.3954]])


In [28]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)

tensor([[ 0.7458,  1.4097,  1.0100],
        [ 1.0252,  0.6327,  0.8803],
        [ 1.3238,  0.6725,  1.2268],
        [ 1.0162,  1.4206,  0.7989],
        [ 0.9007,  0.9021,  1.3954]])

In [29]:
print('y = ', y)
print(y.add(5))
print('y = ', y)
print(y.add(x))
print('y = ', y)
print(y.add_(5)) # _가 붙는 경우는 y를 변경함
print('y = ', y)

y =  tensor([[ 0.0566,  0.6377,  0.7248],
        [ 0.8510,  0.5347,  0.8384],
        [ 0.5616,  0.5559,  0.3589],
        [ 0.2892,  0.5726,  0.1048],
        [ 0.5632,  0.2283,  0.7200]])
tensor([[ 5.0566,  5.6377,  5.7248],
        [ 5.8510,  5.5347,  5.8384],
        [ 5.5616,  5.5559,  5.3589],
        [ 5.2892,  5.5726,  5.1048],
        [ 5.5632,  5.2283,  5.7200]])
y =  tensor([[ 0.0566,  0.6377,  0.7248],
        [ 0.8510,  0.5347,  0.8384],
        [ 0.5616,  0.5559,  0.3589],
        [ 0.2892,  0.5726,  0.1048],
        [ 0.5632,  0.2283,  0.7200]])
tensor([[ 0.7458,  1.4097,  1.0100],
        [ 1.0252,  0.6327,  0.8803],
        [ 1.3238,  0.6725,  1.2268],
        [ 1.0162,  1.4206,  0.7989],
        [ 0.9007,  0.9021,  1.3954]])
y =  tensor([[ 0.0566,  0.6377,  0.7248],
        [ 0.8510,  0.5347,  0.8384],
        [ 0.5616,  0.5559,  0.3589],
        [ 0.2892,  0.5726,  0.1048],
        [ 0.5632,  0.2283,  0.7200]])
tensor([[ 5.0566,  5.6377,  5.7248],
        [ 5.8510, 

In [30]:
# Numpy처럼 index 접근이 가능하다
print(x[:, 1])

tensor([ 0.7720,  0.0980,  0.1166,  0.8480,  0.6738])


In [31]:
# resize나 reshape는 view로 한다.
x = torch.rand(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [32]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([ 0.5556])
0.5555672645568848


In [37]:
# Torch To Numpy
a = torch.ones(5)
b = a.numpy()
print(a)
print(b)

# Numpy 와 torch는 같은 메모리를 공유하기 때문에 하나를 변경하면 다른 것도 변경된다.
a.add_(1)
print("==============================")

print(a)
print(b)


tensor([ 1.,  1.,  1.,  1.,  1.])
[ 1.  1.  1.  1.  1.]
tensor([ 2.,  2.,  2.,  2.,  2.])
[ 2.  2.  2.  2.  2.]


In [39]:
# Numpy To Torch
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

# CharTensor를 제외한 CPU의 모든 Tensors는 NumPy로 변환하고 지원합니다.
np.add(a, 1, out=a)

print("==============================")

print(a)
print(b)


[ 1.  1.  1.  1.  1.]
tensor([ 1.,  1.,  1.,  1.,  1.], dtype=torch.float64)
[ 2.  2.  2.  2.  2.]
tensor([ 2.,  2.,  2.,  2.,  2.], dtype=torch.float64)


In [41]:
# CUDA Tensor
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.rand(5, 3)
    y = torch.rand(5, 3, device=device) # 바로 옮기기
    x.to(device) # GPU로 옮기기
    
    z = x + y
    
    print(z)
    print(z.to("cpu", torch.double))
    

RuntimeError: Error attempting to use dtype torch.float32 with layout torch.strided and device type CUDA.  Torch not compiled with CUDA enabled.
